# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_grpc/grpc/message_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$message_grpc/grpc/message_grpc.proto\x12\x19\x63ompany_back.message_grpc\x1a\x1bgoogle/protobuf/empty.proto"#\n\x15MessageDestroyRequest\x12\n\n\x02id\x18\x01 \x01(\x05"\x14\n\x12MessageListRequest"R\n\x13MessageListResponse\x12;\n\x07results\x18\x01 \x03(\x0b\x32*.company_back.message_grpc.MessageResponse"v\n\x1bMessagePartialUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63hat\x18\x02 \x01(\x03\x12\x0c\n\x04user\x18\x03 \x01(\x03\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x1e\n\x16_partial_update_fields\x18\x05 \x03(\t"I\n\x0eMessageRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63hat\x18\x02 \x01(\x03\x12\x0c\n\x04user\x18\x03 \x01(\x03\x12\x0f\n\x07message\x18\x04 \x01(\t"f\n\x0fMessageResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63hat\x18\x02 \x01(\x03\x12\x0c\n\x04user\x18\x03 \x01(\x03\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x11\n\x04\x64\x61te\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_date"$\n\x16MessageRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xfd\x04\n\x11MessageController\x12\x61\n\x06\x43reate\x12).company_back.message_grpc.MessageRequest\x1a*.company_back.message_grpc.MessageResponse"\x00\x12U\n\x07\x44\x65stroy\x12\x30.company_back.message_grpc.MessageDestroyRequest\x1a\x16.google.protobuf.Empty"\x00\x12g\n\x04List\x12-.company_back.message_grpc.MessageListRequest\x1a..company_back.message_grpc.MessageListResponse"\x00\x12u\n\rPartialUpdate\x12\x36.company_back.message_grpc.MessagePartialUpdateRequest\x1a*.company_back.message_grpc.MessageResponse"\x00\x12k\n\x08Retrieve\x12\x31.company_back.message_grpc.MessageRetrieveRequest\x1a*.company_back.message_grpc.MessageResponse"\x00\x12\x61\n\x06Update\x12).company_back.message_grpc.MessageRequest\x1a*.company_back.message_grpc.MessageResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "message_grpc.grpc.message_grpc_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_MESSAGEDESTROYREQUEST"]._serialized_start = 96
    _globals["_MESSAGEDESTROYREQUEST"]._serialized_end = 131
    _globals["_MESSAGELISTREQUEST"]._serialized_start = 133
    _globals["_MESSAGELISTREQUEST"]._serialized_end = 153
    _globals["_MESSAGELISTRESPONSE"]._serialized_start = 155
    _globals["_MESSAGELISTRESPONSE"]._serialized_end = 237
    _globals["_MESSAGEPARTIALUPDATEREQUEST"]._serialized_start = 239
    _globals["_MESSAGEPARTIALUPDATEREQUEST"]._serialized_end = 357
    _globals["_MESSAGEREQUEST"]._serialized_start = 359
    _globals["_MESSAGEREQUEST"]._serialized_end = 432
    _globals["_MESSAGERESPONSE"]._serialized_start = 434
    _globals["_MESSAGERESPONSE"]._serialized_end = 536
    _globals["_MESSAGERETRIEVEREQUEST"]._serialized_start = 538
    _globals["_MESSAGERETRIEVEREQUEST"]._serialized_end = 574
    _globals["_MESSAGECONTROLLER"]._serialized_start = 577
    _globals["_MESSAGECONTROLLER"]._serialized_end = 1214
# @@protoc_insertion_point(module_scope)
